### ISSUE TITLE
Swift Package offer

### ISSUE THREAD

**Issue by neodave** [dragosrobertn/KNContactsPicker#2]
Hello
I came across this project and it has been an almost perfect fit for us, thank you. We needed to add some functionality and have started moving internally to Swift Packages. I didn't have any trouble converting your project to a package, and would be happy to help you do so if interested. Ours is private and modified, but I could easily create a package and example project for you if interested.
Cheers
Dave

**Comment by dragosrobertn** [comment]
Hi @neodave,

Thank you for the kind words. Sure, feel free to post here any steps I could take to implement Swift Package support and will do so. 
If there are any feature requests you think this could do with, do let me know.

**Comment by neodave** [comment]
Great! What I will do is simply convert your current example app into the app and a separate Swift Package. The wonderful thing is that it eliminates the whole CocoaPod thing for beginners. The example app simply pulls in the framework at launch. 

We are heavily adapting your work to include a couple features, specifically the requirement that a contact have a valid email address, and if they have more than one to pick one. I am about to talk to the other dev, but I think we had to break up your logic a bit. You gather that contacts in the nav view, but sort and search them in the other view controller. That was causing us some issues tracking selected contacts through it all as we had them deal with the email issues. Let me see what the final result is and maybe I can share some of that work if you are interested. 

But simply as a thank you for the great head start I will get your package done for you. Expect it within the week.

**Comment by neodave** [comment]
Actually I just went ahead a did it. Could you create a branch other than Master I can put a PR into? Maybe something like SwiftPackage? I've already converted the example app. And I created the package and pushed it to our repo as a temp solution. So when I push the example app back to you it won't include any of the cocoa pod or framework stuff. Just a package entry in settings, and the rest takes care of itself :) 

Once you see it working just copy the actual framework to your repo and link to that. I will remove our copy once you have it up and running to avoid confusion

**Comment by neodave** [comment]
Yup, just tested it. Works great. Here is how your project will look using the package system. Much cleaner!
![Screen Shot 2020-03-05 at 10 03 26 AM](https://user-images.githubusercontent.com/16582585/76000212-fda2da80-5ec8-11ea-9923-f31a7061b05f.png)

**Comment by dragosrobertn** [comment]
I have just created the `swift-package` branch for you.
Amazing work! Thank you!

**Comment by neodave** [comment]
OK I am ready to push my changes to that branch, but I don't have permission. I think you need to add me to that branch or something. Git can be confusing. Just use this account neodave, that is what I will be pushing from

**Comment by dragosrobertn** [comment]
Hey,
I think you have to first fork the repo, commit against your version and then submit a pull request.

Let me know if that works.

**Comment by neodave** [comment]
Ah, the makes sense

**Comment by dragosrobertn** [comment]
I have just merged your pull request. Apologies it took so long. Will look into merging it into master in due course. Feel free to continue contributing :)

**Comment by neodave** [comment]
Great, let me know if you find any issues

**Comment by neodave** [comment]
We did find a weird permission bug that is not included in this. I would have to ask the other dev, but basically your package will show no connections on first launch after asking for permissions or if unsure. We fixed it our branch, but I am pretty sure it was even in your example app.

**Comment by dragosrobertn** [comment]
Yes, I believe this was on my To Do List. :)
